sudo: required

language: bash

services:
  - docker

branches:
  only:
  - master

install:
  - docker build -t x86_64 - < Dockerfile.dev.x86_64.ubuntu.xenial

script:
  - docker run -i --rm x86_64 /bin/bash --version
